# Generated by Django 4.0.3 on 2022-04-12 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spostinfo', models.CharField(max_length=64)),
                ('spostuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_postid_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postid_like', to='network.postinfo')),
                ('s_user_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postuser_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_comment', models.CharField(max_length=64)),
                ('s_postid_comemnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postid_comment', to='network.postinfo')),
                ('s_user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postuser_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
