# Generated by Django 4.0.3 on 2022-04-12 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_postinfo_postlike_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinfo',
            name='sposttime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
