# Generated by Django 4.0.3 on 2022-04-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_postinfo_sposttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='s_postid_like',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='s_user_like',
        ),
        migrations.AddField(
            model_name='postinfo',
            name='spostlike',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
